import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg={"black"}>
        <img
          width={"60%"}
          src="/Assets/Logo/Logo Mr & Ms UMN 2023 - Circle.png"
        />
        <p className={styles.text_maintenance}>
          Mohon Maaf Website Mr. & Ms. UMN 2023 sedang dalam masa Maintenance
          silahkan kembali lagi nanti
        </p>
      </Box>
    </>
  );
}
