import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Flex, Img, Text, Heading } from "@chakra-ui/react";
import { useState, useRef, useEffect } from "react";
import react from "react";
const inter = Inter({ subsets: ["latin"] });


const getWindowDimensions = () => {
  const { innerWidth: width, innerHeight: height } = window;
  return {
    width,
    height
  };
}

export default function Home(props: any) {

  const [bgWidth, setBgWidth] = useState(1536);
  const [left, setLeft] = useState(0);
  const [right, setRight] = useState(0);

  const hasti = useRef<HTMLImageElement>();
  const rightTree = useRef<HTMLImageElement>();
  const leftTree = useRef<HTMLImageElement>();  

  const shiningSoonImage = useRef<HTMLImageElement>();
  const MRMS =  useRef<HTMLImageElement>();

  const handleScroll = () => {
    const position = window.pageYOffset;
  }

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    }
  }, []);


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        minH={"100vh"}
        w='100%'
        h='1500px'
        bg="black"
        flexDirection={'column'}
        alignItems={"center"}
        justifyContent={"flex-start"}
        flexDir={"column"}
        top={'0'}
        overflowX={'hidden'}
        >
            <Flex h='100vh' w='100%' position={'fixed'} top={'0'} flexDirection={'column'} alignItems={'center'}>
            {/* <Flex h='100vh' w='100%' position={'fixed'} top={'0'} flexDirection={'column'} alignItems={'center'} backgroundImage={"/Assets/Images/hasti4k.png"} backgroundPosition={'center'} backgroundSize={'cover'}> */}
              
              <Img ref={hasti} className={styles.bgImage} src="/Assets/Images/hasti4k.png" objectFit={'cover'} h='100%' w={bgWidth} position='absolute' zIndex={-2}></Img>
              <Flex w='100%' h='100%' maxW={'1536px'} minW={'1536px'} position='absolute' zIndex={-2} flexDirection={'column'} alignItems='center' justifyContent='center'>
                {/* Backgrounds */}
                <Img ref={rightTree} right={right}  src="/Assets/Images/leaf-left.png" objectFit={'cover'} w='50%' h='100vh'  position='absolute' zIndex={-2}></Img>          
                <Img ref={leftTree} left={left} src="/Assets/Images/leaf-right.png" objectFit={'cover'} w='50%' h='100vh'  position='absolute' zIndex={-2}></Img>            

                {/* Dynamic Content */}
                {/* <Img mb='100px' h='200px' w='200px' src="/Assets/Images/shinning soon.png"></Img> */}
                {/* <Img mb='100px' h='200px' w='200px' src="/Assets/Images/logo mr ms.png"></Img>                 */}


              </Flex>              
            </Flex>
        </Flex>
    </div>
  );
}

// export async function getStaticProps() {
//   const res = await fetch("http://localhost:3000/api/hello");
//   const message = await res.json();
//   return {
//     props: {
//       message,
//     },
//   };
// }
